import React from 'react';
import StatCard from '../data-display/StatCard';
import { FileText, Sparkles, CheckCircle2, PlayCircle, ShieldAlert, Percent } from 'lucide-react';
import { formatNumber } from '../../data/dashboardData';

export default function AuditOverview({
  totalCount = 1284,
  recommendationsCount = 347,
  approvalsCount = 218,
  simulationsCount = 205,
  safetyBlocksCount = 19
}) {
  const blockRate = ((safetyBlocksCount / totalCount) * 100).toFixed(1);

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <StatCard 
          title="Total Events"
          value={formatNumber(totalCount)}
          description="Total audit log entries"
          icon={FileText}
        />
        <StatCard 
          title="AI Recommendations"
          value={formatNumber(recommendationsCount)}
          change="Automated AI suggestions"
          changeType="positive"
          description="Generated by AI Agent"
          icon={Sparkles}
        />
        <StatCard 
          title="Merchant Approvals"
          value={formatNumber(approvalsCount)}
          change="Human-in-the-loop signoff"
          changeType="positive"
          description="Approved recovery actions"
          icon={CheckCircle2}
        />
        <StatCard 
          title="Simulations"
          value={formatNumber(simulationsCount)}
          change="Sandbox mode"
          changeType="neutral"
          description="Executed simulations"
          icon={PlayCircle}
        />
        <StatCard 
          title="Safety Blocks"
          value={formatNumber(safetyBlocksCount)}
          change={`${blockRate}% block rate`}
          changeType="danger"
          description="Guardrail blocked actions"
          icon={ShieldAlert}
        />
      </div>
    </div>
  );
}
